### ISSUE TITLE
Infinite loop in prism-match

### ISSUE THREAD

**Issue by danielneal** [alphapapa/prism.el#26]
I've been using prism on a previous version very successfully, mainly to highlight clojure code. 
I recently upgraded emacs to 29.1 and prism to the latest version, but now I get the following error quite frequently:

Error during redisplay: (jit-lock-function 190939) signaled (error "prism: Infinite loop detected in ‘prism-match’ (buffer:#<buffer api.clj> point:191160).  Please report this bug")

**Comment by alphapapa** [comment]
Hi Daniel,

Without a sample of the source code the loop is happening on, there's not much I can do.  If you can isolate the problem to a minimal example that causes the error, that would be great; or at least, show the whole buffer that causes it.

Also, please confirm that the error happens in a clean Emacs configuration, with only the `prism` package installed.  I recommend using this script to make it easy: https://github.com/alphapapa/with-emacs.sh  e.g. just run `with-emacs.sh -i prism`.

Thanks.

**Comment by danielneal** [comment]
Hi Adam, 

Thanks for that - with the clean install, the file colorizes fine without an infinite loop, so I guess I'm on my own with this one.
Dang!

**Comment by alphapapa** [comment]
Hmm, well, I'm guessing that it will happen again as you scroll around randomly in the file that caused the error before.  If it does, please take note of the point position in the error message and take a look at the file there; maybe there's an unusual construct that isn't accounted for in the code.

Another possibility is that, since syntax tables are used by `prism` to do some of the parsing, you might have upgraded the major mode, which is generally responsible for the syntax tables, and that might have affected how `prism` behaves. making the bug go away or, er, hide for a while.  :)

Anyway, please let me know if it happens again.  Thanks.

**Comment by alphapapa** [comment]
Hi Daniel,

Thanks, that ECM made it easy to understand and solve.  This commit seems to solve it for me, testing the same ECM: https://github.com/alphapapa/prism.el/commit/a04e95729b4200833398d97288d5f3ece944304a Please try it and let me know if it solves it for you, and whether it also seems to work normally in other cases (this code is tricky, and it's easy to fix one thing and break another).

**Comment by danielneal** [comment]
Hi Adam, 

I've checked that out and it fixes the problem and my large file colorizes correctly. 

Thanks so much for the quick fix, and for making such a fun and colorful package :)

Daniel

**Comment by alphapapa** [comment]
Thanks, Daniel, these kinds of bugs have been hard to track down; couldn't have done it without your help.  And I'm glad to hear from another user who likes using it.  I really think it is a fundamental aid to Lisp editing, but of course, "there's no accounting for taste."  Cheers!

**Comment by alphapapa** [comment]
I just realized that the fix for this hasn't been merged, probably because the issue was closed and I didn't see it on my issues list anymore.  :)
